#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022 Intel Corporation.

set -e

DICT_URL="https://raw.githubusercontent.com/codespell-project/codespell/master/codespell_lib/data/dictionary.txt"
SPELLING_URL="https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt"
STRUCTS_URL="https://raw.githubusercontent.com/torvalds/linux/master/scripts/const_structs.checkpatch"
CHECKPATH_URL="https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl"

sudo apt update && \
  apt install -y --no-install-recommends \
  python3 python3-pip python3-git python3-ply \
  git shellcheck perl codespell wget

sudo mkdir -p /usr/share/codespell
sudo wget "$DICT_URL" -O /usr/share/codespell/dictionary.txt
sudo wget "$SPELLING_URL" -O /usr/bin/spelling.txt
sudo wget "$STRUCTS_URL" -O /usr/bin/const_structs.checkpatch
sudo wget "$CHECKPATH_URL" -O /bin/checkpatch.pl
sudo chmod +x /bin/checkpatch.pl
